### ISSUE TITLE
关于备份相关页面的一点建议

### ISSUE THREAD

**Issue by yingziwu** [greatghoul/sibi#41]
1. 建议对于本仓库涉及的页面使用 https://archive.org/ 进行备份，以免相关页面删除与篡改。
1. 对于由于`robots.txt`限制，archive.org无法备份的页面，能否参考[#40](https://github.com/greatghoul/sibi/pull/40)，在本仓库某一目录下进行备份。

**Comment by greatghoul** [comment]
感谢建议，1 具体应该怎么做呢？之前的确有碰到链接失效的情况。

**Comment by yingziwu** [comment]
@greatghoul 
回复晚了，可以参考[这个页面](http://www.bitsgalore.org/2014/08/02/How-to-save-a-web-page-to-the-Internet-Archive)把页面保存到  https://archive.org/  。

我用的是方法一，后头两个方法没有试过，不知道能不能用。

**Comment by yingziwu** [comment]
另，最近又发现了一个问题，
例如[续 就算老公一毛钱股份都没拿到，在我心里，他依然是最牛逼的创业者](https://www.v2ex.com/t/342559)这个帖子，该帖子已经进入了水区（目前archive.org内也无任何存档），不登录便无法访问，虽然用[API](https://www.v2ex.com/api/topics/show.json?id=342559)仍然可以获取帖子的内容，但该页面本身已经无法被快照存储了。

对于这种情况，是否需要像对微信一样，单独在仓库里头存储？还是保存API结果便可以了？

**Comment by greatghoul** [comment]
暂时像微信那样来处理吧，等想到好的办法了，可以再置换。

**Comment by yingziwu** [comment]
@greatghoul 
已对这些网页提了PR（ #45 ）了
