### ISSUE TITLE
V2 曝光 Spammer 信息

### ISSUE THREAD

**Issue by NeverBehave** [greatghoul/sibi#46]
原帖：
https://www.v2ex.com/t/443087#41

后续：
https://www.v2ex.com/t/443231

archive.fo 有备份

**Comment by greatghoul** [comment]
可否提交个 PR?

**Comment by GavinFoo** [comment]
http://ww1.sinaimg.cn/large/5dcb16dfly1fpxr8uvmumj20ct04z0sv.jpg
http://ww1.sinaimg.cn/large/5dcb16dfly1fpxr94gefmj20gh04xjrk.jpg
已经快连续一天出现 502  504 了

**Comment by greatghoul** [comment]
@GavinFoo 我今天访问 v 站也一直 502

**Comment by NeverBehave** [comment]
我把位置放反了……最新的应该放在前面 @greatghoul  可以改一下吗

**Comment by greatghoul** [comment]
@NeverBehave 改了。
