### ISSUE TITLE
极路由泄密事件

### ISSUE THREAD

**Issue by zuoa** [greatghoul/sibi#5]
极路由泄密事件 (2013.08)
 - [极路由窃取用户信息，诸位小心！](https://www.v2ex.com/t/77921)
 - [不敢为产品剖腹的合伙人不是好的创业者](https://www.v2ex.com/t/78001)
 - [极路由事件后续](https://www.v2ex.com/t/77947)

**Comment by zuoa** [comment]
懒得PR了

**Comment by greatghoul** [comment]
已经有人提交了 pr 啦😄
