### ISSUE TITLE
中医撕逼事件

### ISSUE THREAD

**Issue by 9bie** [greatghoul/sibi#52]
https://www.v2ex.com/t/538109

**Comment by NeverBehave** [comment]
于 02/24/2019 16:22 UTC-4 的截图
![第一页](https://user-images.githubusercontent.com/17120571/53305498-4a80b980-3850-11e9-8941-0921e74bb607.png)
![第二页](https://user-images.githubusercontent.com/17120571/53305505-553b4e80-3850-11e9-8e7d-9354083dff07.png)

**Comment by greatghoul** [comment]
一直以来竟然忽略了 issues, 存档放在 issues 是个好主意呀，不占用 repo 空间。

**Comment by greatghoul** [comment]
[其实中国如果想在未来一代人身上大幅降低癌症发病率也很简单，做到以下几条就可以： - V2EX.pdf](https://github.com/greatghoul/sibi/files/2911248/-.V2EX.pdf)

**Comment by NeverBehave** [comment]
> 一直以来竟然忽略了 issues, 存档放在 issues 是个好主意呀，不占用 repo 空间。

我也是这样想的，不过这样子的话不好批量备份
题外话：repo最大100G无所谓的吧

**Comment by greatghoul** [comment]
repo 太大的话，有的网友想要 fork 编辑就会比较累。

**Comment by NeverBehave** [comment]
> repo 太大的话，有的网友想要 fork 编辑就会比较累。

这样子的话，fork并不会把内容一起复制一遍

**Comment by greatghoul** [comment]
仓库文件只要包含内容的索引就好了。

**Comment by NeverBehave** [comment]
> 仓库文件只要包含内容的索引就好了。

那就先这样子好了
还可以做的事情就是，如果以后还继续用issue的话：
做个机器人hook issue，检测链接并自动生成图片和PDF回复在下方
